[package]
name = "ream-syncer"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
devnet5 = ["ream-storage/devnet5", "ream-p2p/devnet5"]

[dependencies]
alloy-primitives.workspace = true
anyhow.workspace = true
ethereum_ssz.workspace = true
futures.workspace = true
libp2p.workspace = true
libp2p-identity.workspace = true
libp2p-mplex.workspace = true
tokio.workspace = true
tracing.workspace = true
tree_hash.workspace = true

# ream dependencies
ream-bls.workspace = true
ream-chain-beacon.workspace = true
ream-consensus-beacon.workspace = true
ream-consensus-misc.workspace = true
ream-executor.workspace = true
ream-network-spec.workspace = true
ream-p2p.workspace = true
ream-polynomial-commitments.workspace = true
ream-req-resp.workspace = true
ream-storage.workspace = true

[dev-dependencies]
discv5.workspace = true
kzg.workspace = true
parking_lot.workspace = true
ream-execution-rpc-types.workspace = true
ream-operation-pool.workspace = true
ream-peer.workspace = true
ream-sync-committee-pool.workspace = true
tempfile.workspace = true

[lints]
workspace = true
